GomezGallery.WebUI/Models/CartIndexViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using GomezGallery.Domain.Entities;

namespace GomezGallery.WebUI.Models
{
	public class CartIndexViewModel
	{
		public Cart Cart { get; set; }

		public string ReturnUrl { get; set; }
	}
}

GomezGallery.WebUI/Models/LoginViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace GomezGallery.WebUI.Models
{
	public class LoginViewModel
	{
		[Required]
		public string UserName { get; set; }

		[Required]
		public string Password { get; set; }
	}
}

GomezGallery.WebUI/Models/PagingInfo.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace GomezGallery.WebUI.Models
{
	public class PagingInfo
	{
		public int TotalItems { get; set; }
		public int ItemsPerPage { get; set; }
		public int CurrentPage { get; set; }
		public int TotalPages
		{
			get
			{
				return (int)Math.Ceiling((decimal)TotalItems / ItemsPerPage);
			}
		}
	}
}

GomezGallery.WebUI/Models/PictureListViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using GomezGallery.Domain.Entities;

namespace GomezGallery.WebUI.Models
{
	public class PictureListViewModel
	{
		public IEnumerable<Picture> Pictures { get; set; }

		public PagingInfo PagingInfo { get; set; }

		// add current category
		public string CurrentCategory { get; set; }
	}
}

GomezGallery.WebUI/Controllers/AccountController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using GomezGallery.WebUI.Infrastructure.Abstract;
using GomezGallery.WebUI.Models;

namespace GomezGallery.WebUI.Controllers
{
    public class AccountController : Controller
    {
		IAuthProvider authProvider;

		public AccountController(IAuthProvider auth)
		{
			authProvider = auth; ;
		}

		public ViewResult Login()
		{
			return View();
		}

		[HttpPost]
		public ActionResult Login(LoginViewModel model, string returnUrl)
		{
			if (ModelState.IsValid)
			{
				// proceed with admin dashboard
				if (authProvider.Authenticate(model.UserName, model.Password))
				{
					return Redirect(returnUrl ?? Url.Action("Index", "Admin"));
				}

				// username or password wrong
				else
				{
					ModelState.AddModelError("", "Incorrect username or password");
					return View();
				}
			}
			else
			{
				return View();
			}
		}
	}
}

GomezGallery.WebUI/Controllers/AdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using GomezGallery.Domain.Abstract;
using GomezGallery.Domain.Entities;

namespace GomezGallery.WebUI.Controllers
{
	[Authorize]
    public class AdminController : Controller
    {
		private IPictureRepository repository;

		public AdminController(IPictureRepository repo)
		{
			repository = repo;
		}

		public ViewResult Index()
		{
			return View(repository.Pictures);
		}

		public ViewResult Edit(int pictureID)
		{
			Picture picture = repository.Pictures.FirstOrDefault(p => p.PictureID == pictureID);

			return View(picture);
		}

		[HttpPost]
		public ActionResult Edit(Picture picture, HttpPostedFileBase image = null)
		{
			if (ModelState.IsValid)
			{
				if (image != null)
				{
					picture.ImageMimeType = image.ContentType;
					picture.ImageData = new byte[image.ContentLength];
					image.InputStream.Read(picture.ImageData, 0, image.ContentLength);
				}

				repository.SavePicture(picture);
				TempData["message"] = string.Format("{0} has been saved", picture.Name);
				return RedirectToAction("Index");
			}
			else
			{
				return View(picture);
			}
		}

		public ViewResult Create()
		{
			return View("Edit", new Picture());
		}

		public ActionResult Delete(int pictureID)
		{
			Picture deletedPicture = repository.DeletePicture(pictureID);

			if (deletedPicture != null)
			{
				TempData["message"] = string.Format("{0} has been deleted", deletedPicture.Name);
			}

			return RedirectToAction("Index");
		}
	}
}

GomezGallery.WebUI/Controllers/CartController.cs
using GomezGallery.Domain.Abstract;
using GomezGallery.Domain.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using GomezGallery.WebUI.Models;

namespace GomezGallery.WebUI.Controllers
{
	public class CartController : Controller
	{
		private IPictureRepository repository;
		private IOrderProcessor orderProcessor;

		public CartController(IPictureRepository repo, IOrderProcessor proc)
		{
			repository = repo;
			orderProcessor = proc;
		}

		// Add to cart
		public RedirectToRouteResult AddToCart(Cart cart, int pictureID, string returnUrl)
		{
			Picture picture = repository.Pictures.FirstOrDefault(p => p.PictureID == pictureID);

			if (picture != null)
			{
				cart.AddItem(picture, 1);
			}

			return RedirectToAction("Index", new { returnUrl });
		}

		// Remove from cart
		public RedirectToRouteResult RemoveFromCart(Cart cart, int pictureID, string returnUrl)
		{
			Picture picture = repository.Pictures.FirstOrDefault(p => p.PictureID == pictureID);

			if (picture != null)
			{
				cart.RemoveLine(picture);
			}

			return RedirectToAction("Index", new { returnUrl });
		}

		public ViewResult Index(Cart cart, string returnUrl)
		{
			return View(new CartIndexViewModel
			{
				ReturnUrl = returnUrl,
				Cart = cart
			});
		}

		public PartialViewResult Summary(Cart cart)
		{
			return PartialView(cart);
		}

		public ViewResult Checkout()
		{
			return View(new ShippingDetails());
		}

		[HttpPost]
		public ViewResult Checkout(Cart cart, ShippingDetails shippingDetails)
		{
			// empty cart check
			if (cart.Lines.Count() == 0)
			{
				ModelState.AddModelError("", "Sorry, your cart is empty!");
			}

			// check for errors in ModelState
			if (ModelState.IsValid)
			{
				orderProcessor.ProcessOrder(cart, shippingDetails);
				cart.Clear();
				return View("Completed", shippingDetails);
			}
			else
			{
				return View(shippingDetails);
			}
		}
	}
}

GomezGallery.WebUI/Controllers/NavController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using GomezGallery.Domain.Abstract;

namespace GomezGallery.WebUI.Controllers
{
	public class NavController : Controller
	{
		private IPictureRepository repository;

		public NavController(IPictureRepository repo)
		{
			repository = repo;
		}
		public PartialViewResult Menu(string category = null)
		{
			ViewBag.SelectedCategory = category;

			IEnumerable<string> categories = repository.Pictures.Select(x => x.Category)
				 .Distinct()
				 .OrderBy(x => x);

			return PartialView(categories);
		}
	}
}

GomezGallery.WebUI/Controllers/PictureController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using GomezGallery.Domain.Abstract;
using GomezGallery.Domain.Entities;
using GomezGallery.WebUI.Models;

namespace GomezGallery.WebUI.Controllers
{
    public class PictureController : Controller
    {
		private IPictureRepository myRepository;

		public PictureController(IPictureRepository pictureRepository)
		{
			this.myRepository = pictureRepository;
		}

		public int PageSize = 3;

		public ViewResult List(string category, int page = 1)
		{
			PictureListViewModel model = new PictureListViewModel
			{
				Pictures = myRepository.Pictures
				.Where(p => category == null || p.Category == category)
				.OrderBy(p => p.PictureID)
				.Skip((page - 1) * PageSize)
				.Take(PageSize),

				PagingInfo = new PagingInfo
				{
					CurrentPage = page,
					ItemsPerPage = PageSize,
					TotalItems = category == null ?
									myRepository.Pictures.Count() :
									myRepository.Pictures.Where(x => x.Category == category).Count()
				},
				CurrentCategory = category
			};

			return View(model);
		}

		public FileContentResult GetImage(int pictureID)
		{
			Picture pic = myRepository.Pictures.FirstOrDefault(p => p.PictureID == pictureID);

			if (pic != null)
			{
				return File(pic.ImageData, pic.ImageMimeType);
			}
			else
			{
				return null;
			}
		}
	}
}

GomezGallery.WebUI/Views/Admin/Edit.cshtml
@model GomezGallery.Domain.Entities.Picture

@{
	if (Model.PictureID != 0)
	{
		ViewBag.Title = "Admin: Edit " + Model.Name;
	}
	else
	{
		ViewBag.Title = "Admin: Add New Picture";
	}
	Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<div class="card">
	<div class="card-header">
		<h3>@ViewBag.Title</h3>
	</div>

	@using (Html.BeginForm("Edit", "Admin", FormMethod.Post, new { enctype = "multipart/form-data" }))
	{
		<div class="card-body">
			@*Hide the product ID*@
			@Html.HiddenFor(x => x.PictureID)

			@*Display the other fields, pre-filled in*@
			@foreach (var property in ViewData.ModelMetadata.Properties)
			{
				switch (property.PropertyName)
				{
					case "PictureID":
					case "ImageData":
					case "ImageMimeType":
						break;
					default:
						<div class="mb-3">
							<label class="form-label">
								@(property.DisplayName ?? property.PropertyName)
							</label>

							@if (property.PropertyName == "Description")
							{
								@Html.TextArea(property.PropertyName, null, new { @class = "form-control", rows = 5 })
							}
							else
							{
								@Html.TextBox(property.PropertyName, null, new { @class = "form-control" })
							}

							@Html.ValidationMessage(property.PropertyName)

						</div>
						break;
				}
			}
			<div class="mb-3">
				<label class="form-label">Image</label>
				<div style="position:relative;">
					<a class="btn btn-secondary" href="javascript:;">
						Choose File
						<input type="file" name="Image" size="40"
							   style="position:absolute;z-index:2;top:0;left:0;opacity:0;
						background-color:transparent;color:transparent;"
							   onchange='$("upload-file-info").html($(this).val());' />
					</a>
					<span class="form-label label-info" id="upload-file-info"></span>
				</div>

				@if (Model.ImageData == null)
				{
					<div class="form-text">No Image</div>
				}
				else
				{
					<img class="img-thumbnail" width="150" height="150"
						 src='@Url.Action("GetImage", "Picture", new { Model.PictureID })' />
				}
			</div>
		</div>


		<div class="card-footer">
			<input type="submit" value="Save" class="btn btn-primary" />
			@Html.ActionLink("Cancel and return to list", "Index", null, new { @class = "btn btn-primary" })
		</div>
	}
</div>

GomezGallery.WebUI/Views/Admin/Index.cshtml
@model IEnumerable<GomezGallery.Domain.Entities.Picture>

@{
	ViewBag.Title = "Admin: Index";
	Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<div class="card">
	<div class="card-header">
		<h3>All Products</h3>
	</div>

	<div class="card-body">
		<table class="table table-striped table-condensed table-bordered">
			<tr>
				<th class="text-right">ID</th>
				<th>Name</th>
				<th class="text-right">Price</th>
				<th class="text-center">Actions</th>
			</tr>

			@foreach (var item in Model)
			{
				<tr>
					<td>@item.PictureID</td>
					<td>@Html.ActionLink(item.Name, "Edit", new { item.PictureID })</td>
					<td>@item.Price.ToString("c")</td>
					<td class="text-center">
						@using (Html.BeginForm("Delete", "Admin"))
						{
							@Html.Hidden("PictureID", item.PictureID)
							<input type="submit"
								   class="btn btn-danger"
								   value="Delete" />
						}
					</td>
				</tr>
			}
		</table>
	</div>
</div>

<div class="card-footer text-center">
	@Html.ActionLink("Add a new product", "Create", null, new { @class = "btn btn-primary" })
</div>

GomezGallery.WebUI/Views/Cart/Checkout.cshtml
@model GomezGallery.Domain.Entities.ShippingDetails

@{
	ViewBag.Title = "Gomez Gallery: Checkout";
}

<h2>Checkout now</h2>

<p>
	Please enter your details, and we'll ship your goods right away!
</p>

@using (Html.BeginForm())
{
	@Html.ValidationSummary()

	<h3>Ship to</h3>
	<div class="form-group">
		<label>Name:</label>
		@Html.TextBoxFor(x => x.Name, new { @class = "form-control" })
	</div>

	<h3>Address</h3>
	foreach (var property in ViewData.ModelMetadata.Properties)
	{
		if (property.PropertyName != "Name" && property.PropertyName != "GiftWrap")
		{
			<div class="form-group">
				<label>@(property.DisplayName ?? property.PropertyName)</label>
				@Html.TextBox(property.PropertyName, null, new { @class = "form-control" })
			</div>
		}
	}

	<h3>Options</h3>
	<div class="checkbox">
		<label>
			@Html.CheckBoxFor(x => x.GiftWrap)
			Gift wrap these items
		</label>
	</div>

	<div class="text-center">
		<input class="btn btn-primary" type="submit" value="Complete order" />
	</div>
}

GomezGallery.WebUI/Views/Cart/Completed.cshtml
@model GomezGallery.Domain.Entities.ShippingDetails

@{
	ViewBag.Title = "Completed";
}

<h2>Thank you for your order, @Model.Name! Your order has been successfully completed.</h2>
You will soon receive an email confirmation regarding your purchase. We appriciate your business!

GomezGallery.WebUI/Views/Cart/Index.cshtml
@model GomezGallery.WebUI.Models.CartIndexViewModel

@{
	ViewBag.Title = "Gomez Gallery: Your Cart";
}

<style>
	#cartTable td {
		vertical-align: middle;
	}
</style>

<h2>Your Cart</h2>

<table id="cartTable" class="table">
	<thead>
		<tr>
			<th>Quantity</th>
			<th>Item</th>
			<th class="text-end">Price</th>
			<th class="text-end">Subtotal</th>
		</tr>
	</thead>

	<tbody>
		@foreach (var line in Model.Cart.Lines)
		{
			<tr>
				<td class="text-center">@line.Quantity</td>
				<td>@line.Picture.Name</td>
				<td class="text-end">@line.Picture.Price.ToString("c")</td>
				<td class="text-end">@((line.Quantity * line.Picture.Price).ToString("c"))</td>
				<td>
					@using (Html.BeginForm("RemoveFromCart", "Cart"))
					{
						@Html.Hidden("PictureID", line.Picture.PictureID)
						@Html.HiddenFor(x => x.ReturnUrl)
						<input type="submit" class="btn btn-warning" value="Remove" />
					}
				</td>
			</tr>
		}
	</tbody>

	<tfoot>
		<tr>
			<td colspan="3" class="text-end">Total:</td>
			<td class="text-end">@Model.Cart.ComputeTotalValue().ToString("c")</td>
		</tr>
	</tfoot>
</table>

<div class="text-center">
	<a class="btn btn-primary" href="@Model.ReturnUrl">Continue Shopping</a>
	@Html.ActionLink("Checkout now", "Checkout", null, new { @class = "btn btn-primary" })
</div>

GomezGallery.WebUI/Views/Cart/Summary.cshtml
@model GomezGallery.Domain.Entities.Cart

@*Cart summary*@
<div class="navbar-text navbar-right">
	<b>Your cart: </b>
	@Model.Lines.Sum(x => x.Quantity) items(s),
	@Model.ComputeTotalValue().ToString("c")

	@*Checkout button*@
	@Html.ActionLink("Check Out", "Index", "Cart",
	new { returnUrl = Request.Url.PathAndQuery },
	new { @class = "btn btn-light text-dark ms-2 me-3" })
</div>

GomezGallery.WebUI/Views/Nav/Menu.cshtml
@model IEnumerable<string>

@*Home Button*@
@Html.ActionLink("Home", "List", "Picture", null,
	new { @class = "btn btn-outline-secondary w-100 btn-lg mb-2" })

@*Buttons for each category*@
@foreach (var link in Model)
{
	@Html.RouteLink(link, new
	{
		controller = "Picture",
		action = "List",
		category = link,
		page = 1
	},
	new
		{
			@class = "btn btn-outline-secondary w-100 btn-lg mb-2"
		+ (link == ViewBag.SelectedCategory ? " active" : "")
		})
}

GomezGallery.WebUI/Views/Picture/List.cshtml
@model GomezGallery.WebUI.Models.PictureListViewModel

@{
	ViewBag.Title = "Gomez Gallery";
}

@foreach (var p in Model.Pictures)
{
	@Html.Partial("PictureSummary", p)
}

<div class="btn-group float-end">
	@Html.PageLinks(Model.PagingInfo, x => Url.Action("List", new { page = x, category = Model.CurrentCategory }))
</div>

GomezGallery.WebUI/Views/Shared/PictureSummary.cshtml
@model GomezGallery.Domain.Entities.Picture

<div class="card p-3 bg-light text-dark mb-2">
	<h3>
		<strong>@Model.Name</strong>
		<span class="badge bg-primary float-end">
			@Model.Price.ToString("c")
		</span>
		@if (Model.ImageData != null)
		{
			<div class="pull-left" style="margin-right: 10px">
				<img class="img-thumbnail" width="150" height="150"
					 src='@Url.Action("GetImage", "Picture", new { Model.PictureID })' />
			</div>
		}
	</h3>

	<span class="lead">@Model.Description</span>

	@using (Html.BeginForm("AddToCart", "Cart"))
	{
		<div class="float-end">
			@Html.HiddenFor(x => x.PictureID)
			@Html.Hidden("returnUrl", Request.Url.PathAndQuery)

			<input type="submit" class="btn btn-success" value="Add to cart" />
		</div>
	}
</div>

GomezGallery.WebUI/Views/Shared/_AdminLayout.cshtml
@{
	Layout = null;
}

<!DOCTYPE html>

<html>
<head>
	<link href="~/Content/bootstrap.css" rel="stylesheet" />
	<link href="~/Content/ErrorStyle.css" rel="stylesheet" />
	<meta name="viewport" content="width=device-width" />

	<script src="~/Scripts/jquery-1.4.1.js"></script>
	<script src="~/Scripts/jquery.validate.js"></script>
	<script src="~/Scripts/jquery.validate.unobtrusive.js"></script>

	<title>@ViewBag.Title</title>
</head>
<body>
	<div>
		@if (TempData["message"] != null)
		{
			<div class="alert alert-success">
				@TempData["message"]
			</div>
		}
		@RenderBody()
	</div>
</body>
</html>

GomezGallery.WebUI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<link href="~/Content/bootstrap.css" rel="stylesheet" />
	<link href="~/Content/ErrorStyle.css" rel="stylesheet" />

	<title>@ViewBag.Title </title>
</head>
<body>
	@* Nav bar - displays Gomez Gallery title *@
	<div class="navbar navbar-dark bg-dark">
		<a class="navbar-brand ms-4" href="#">Gomez Gallery</a>
		@Html.Action("Summary", "Cart")
	</div>

	<div class="row border p-3">
		@* Panel to list the categories *@
		<div id="categories" class="col-3">
			@Html.Action("Menu", "Nav")
		</div>


		@* A <div> to display the body *@
		<div class="col-9">
			@RenderBody()
		</div>
	</div>
</body>
</html>